import Combine
import Foundation
import UniformTypeIdentifiers

@MainActor
final class AppModel: ObservableObject {
    @Published var sessions: [ConversationSession]
    @Published var selectedSessionID: ConversationSession.ID?
    @Published var recorderState: RecorderState = .idle
    @Published var liveTranscriptPreview = ""
    @Published var modelAvailability: ModelAvailabilitySummary = .checking
    @Published var generationState: GenerationState = .idle

    private let transcription: TranscriptionProviding
    private let questionGenerator: QuestionGenerating
    private var autoGenerationTask: Task<Void, Never>?
    private var lastAutoGeneratedTranscript = ""

    init(
        transcription: TranscriptionProviding? = nil,
        questionGenerator: QuestionGenerating = FoundationQuestionGenerator()
    ) {
        let firstSession = ConversationSession.sample
        self.sessions = [firstSession]
        self.selectedSessionID = firstSession.id
        self.transcription = transcription ?? LocalSpeechTranscriptionService()
        self.questionGenerator = questionGenerator

        Task {
            await refreshModelAvailability()
        }
    }

    var selectedSession: ConversationSession? {
        guard let selectedSessionID else { return nil }
        return sessions.first { $0.id == selectedSessionID }
    }

    func createSession() {
        let session = ConversationSession(title: "New Conversation")
        sessions.insert(session, at: 0)
        selectedSessionID = session.id
    }

    func select(_ session: ConversationSession) {
        selectedSessionID = session.id
    }

    func toggleRecording() async {
        switch recorderState {
        case .idle, .failed:
            do {
                liveTranscriptPreview = ""
                try await transcription.startLiveTranscription { [weak self] update in
                    Task { @MainActor in
                        guard let self else { return }
                        self.liveTranscriptPreview = update.text
                        self.scheduleAutomaticQuestionGeneration()
                    }
                }
                recorderState = .recording(startedAt: .now)
            } catch {
                recorderState = .failed(error.localizedDescription)
                appendTranscript(text: "Recording could not start: \(error.localizedDescription)", source: .system)
            }
        case .recording:
            let finalText = await transcription.stopLiveTranscription()
            recorderState = .idle
            let textToSave = (finalText ?? liveTranscriptPreview)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            liveTranscriptPreview = ""

            if textToSave.isEmpty {
                appendTranscript(text: "Recording stopped. No local speech was recognized.", source: .system)
            } else {
                appendTranscript(text: textToSave, source: .speaker("Live Audio"))
                scheduleAutomaticQuestionGeneration(delay: 1.0)
            }
        }
    }

    func importAudio(from url: URL) async {
        do {
            let transcriptText = try await transcription.transcribeAudioFile(at: url)
            appendTranscript(text: transcriptText, source: .importedAudio(url.lastPathComponent))
            scheduleAutomaticQuestionGeneration(delay: 1.0)
        } catch {
            appendTranscript(text: "Audio import failed: \(error.localizedDescription)", source: .system)
        }
    }

    func refreshModelAvailability() async {
        modelAvailability = await questionGenerator.availability()
    }

    func generateQuestions() async {
        await generateQuestions(trigger: .manual)
    }

    private func generateQuestions(trigger: GenerationTrigger) async {
        if generationState == .generating {
            return
        }

        guard let session = selectedSession else { return }

        let transcript = currentTranscriptText(for: session)
        guard transcript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false else {
            generationState = .failed("A transcript is needed before questions can be generated.")
            return
        }

        if trigger == .automatic && shouldAutoGenerateQuestions(for: transcript) == false {
            return
        }

        generationState = .generating

        do {
            let questions = try await questionGenerator.generateQuestions(from: transcript)
            updateSelectedSession { selected in
                selected.questionSet = questions
                selected.updatedAt = .now
            }
            lastAutoGeneratedTranscript = transcript
            generationState = .idle
        } catch {
            if trigger == .manual {
                generationState = .failed(error.localizedDescription)
            } else {
                generationState = .idle
            }
        }
    }

    private func appendTranscript(text: String, source: TranscriptSource) {
        updateSelectedSession { selected in
            selected.segments.append(TranscriptSegment(text: text, source: source))
            selected.updatedAt = .now
        }
    }

    private func updateSelectedSession(_ update: (inout ConversationSession) -> Void) {
        guard let selectedSessionID,
              let index = sessions.firstIndex(where: { $0.id == selectedSessionID })
        else {
            return
        }

        update(&sessions[index])
    }

    private func currentTranscriptText(for session: ConversationSession) -> String {
        [session.transcriptText, liveTranscriptPreview]
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { $0.isEmpty == false }
            .joined(separator: "\n")
    }

    private func scheduleAutomaticQuestionGeneration(delay: TimeInterval = 5.0) {
        guard let session = selectedSession else { return }

        let transcript = currentTranscriptText(for: session)
        guard shouldAutoGenerateQuestions(for: transcript) else { return }

        autoGenerationTask?.cancel()
        autoGenerationTask = Task { [weak self] in
            let nanoseconds = UInt64(delay * 1_000_000_000)
            try? await Task.sleep(nanoseconds: nanoseconds)
            guard Task.isCancelled == false else { return }
            await self?.generateQuestions(trigger: .automatic)
        }
    }

    private func shouldAutoGenerateQuestions(for transcript: String) -> Bool {
        let trimmed = transcript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count >= 80 else { return false }

        let previous = lastAutoGeneratedTranscript.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed != previous else { return false }

        if previous.isEmpty {
            return true
        }

        return abs(trimmed.count - previous.count) >= 80
    }
}

private enum GenerationTrigger {
    case manual
    case automatic
}

enum RecorderState: Equatable {
    case idle
    case recording(startedAt: Date)
    case failed(String)

    var label: String {
        switch self {
        case .idle:
            "Ready"
        case .recording:
            "Recording"
        case .failed:
            "Needs attention"
        }
    }
}

enum GenerationState: Equatable {
    case idle
    case generating
    case failed(String)
}
